# Generated by Django 3.0.8 on 2021-03-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_authgroup_authgrouppermissions_authpermission_djangoadminlog_djangocontenttype_djangomigrations_djan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='NetworkFollowUserMtmUser',
        ),
        migrations.DeleteModel(
            name='NetworkLike',
        ),
        migrations.RemoveField(
            model_name='networklikespostmtmlike',
            name='post',
        ),
        migrations.DeleteModel(
            name='NetworkUser',
        ),
        migrations.DeleteModel(
            name='NetworkUserGroups',
        ),
        migrations.DeleteModel(
            name='NetworkUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='NetworkLikesPostMtmLike',
        ),
        migrations.DeleteModel(
            name='NetworkPost',
        ),
    ]
